[program:pregao-ws-gateway]
command=php /home/eskill/htdocs/eskill.com.br/bin/pregao-ws-gateway.php
directory=/home/eskill/htdocs/eskill.com.br
autostart=true
autorestart=true
user=eskill
redirect_stderr=true
stdout_logfile=/home/eskill/htdocs/eskill.com.br/storage/logs/pregao-ws.log
stopwaitsecs=10

[program:pregao-index-tick]
command=php /home/eskill/htdocs/eskill.com.br/bin/pregao-index-tick.php --all --loop --interval=45
directory=/home/eskill/htdocs/eskill.com.br
autostart=true
autorestart=true
user=eskill
redirect_stderr=true
stdout_logfile=/home/eskill/htdocs/eskill.com.br/storage/logs/pregao-tick.log
stopwaitsecs=10
